apiVersion: v1
kind: LimitRange
metadata:
  name: myapp-limits
  namespace: myapp
spec:
  limits:
  - type: Container
    default:              #This will be picked, if your container dont have any LIMITS.
      cpu: "1"            #Max CPU Container gets
      memory: "1Gi"       #Max Memory cotnainer gets
    defaultRequest:
      cpu: "0.5"            #Default CPU Container gets, if we dont define REQUESTS at container level.
      memory: "512Mi"       #Default Memory Container gets, if we dont define REQUESTS at container level.