apiVersion: v1
kind: Pod
metadata:
  name: failtest
  namespace: myapp
spec:
  containers:
  - name: myfirstcontainer
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "2Gi"
        cpu: "2"