apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_USERNAME: "dbadmin"
  DB_PASSWORD: "Password123"

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-secret
# type: Opaque
# data:
#   DB_USERNAME: "ZGJhZG1pbg"
#   DB_PASSWORD: "UGFzc3dvcmQxMjM"


---

apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: myfirstcontainer
    image: busybox
    command: ["sh", "-c", "echo Hello from $DB_USERNAME also here is my password $DB_PASSWORD && sleep 120"]
    envFrom:
      - secretRef:
          name: db-secret
